version: 3

includes:
  users:
    taskfile: microservices/users/Taskfile.users.yaml
  cameras:
    taskfile: microservices/cameras/Taskfile.cameras.yaml
tasks:
  default:
    desc: Список задач
    cmds:
      - task --list
 